# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homedisplay', models.CharField(max_length=10)),
                ('awaydisplay', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boards', models.PositiveSmallIntegerField()),
                ('division', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_club', models.CharField(max_length=50)),
                ('opponent_team', models.CharField(max_length=1)),
                ('venue', models.CharField(choices=[('H', 'Home'), ('A', 'Away')], max_length=1)),
                ('date', models.DateTimeField()),
                ('match_result', models.CharField(blank=True, max_length=1, null=True)),
                ('our_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('their_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('white_on', models.CharField(blank=True, choices=[('O', 'Odd'), ('E', 'Even'), ('U', 'Unknown')], max_length=1, null=True)),
                ('captains_headline', models.TextField()),
                ('captains_comment', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seasons.Campaign')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchtype_code', models.CharField(max_length=6)),
                ('matchtype_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=35)),
                ('initials', models.CharField(max_length=5)),
                ('ECF_reg', models.CharField(max_length=10, null=True)),
                ('active', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.PositiveSmallIntegerField()),
                ('opponent_name', models.CharField(max_length=30)),
                ('opponent_grade', models.PositiveIntegerField(blank=True, null=True)),
                ('boardresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seasons.Boardresult')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seasons.Fixture')),
                ('our_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seasons.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('fullname', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.PositiveSmallIntegerField()),
                ('letter', models.CharField(max_length=1)),
                ('code', models.CharField(max_length=20)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seasons.League')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='gradelist',
            field=models.ManyToManyField(through='Seasons.Grade', to='Seasons.Season'),
        ),
        migrations.AddField(
            model_name='grade',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seasons.Player'),
        ),
        migrations.AddField(
            model_name='grade',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seasons.Season'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='matchtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seasons.MatchType'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seasons.Player'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seasons.Season'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seasons.Team'),
        ),
    ]
